#pragma once
#include "tr_misc.hpp"
#include "tr_level.hpp"
#include "tr_level_data.hpp"

static String get_lara_animation_name(size_t p_animation_id, TRLevelFormat p_level_format) {
	switch(p_animation_id) {
		case 0:
			return "run";
		case 1:
			return "walk_forwards";
		case 2:
			return "walk_stop_right";
		case 3:
			return "walk_stop_left";
		case 4:
			return "walk_to_run_right";
		case 5:
			return "walk_to_run_left";
		case 6:
			return "run_start";
		case 7:
			return "run_to_walk_right";
		case 8:
			return "run_to_stand_left";
		case 9:
			return "run_to_walk_left";
		case 10:
			return "run_to_stand_right";
		case 11:
			return "stand_still";
		case 12:
			return "turn_right_slow";
		case 13:
			return "turn_left_slow";
		case 14:
			return "jump_forward_land_start_unused";
		case 15:
			return "jump_forward_land_end_unused";
		case 16:
			return "run_jump_right_start";
		case 17:
			return "run_jump_right_continue";
		case 18:
			return "run_jump_left_start";
		case 19:
			return "run_jump_left_continue";
		case 20:
			return "walk_forward_start";
		case 21:
			return "walk_forward_start_continue";
		case 22:
			return "jump_forward_to_freefall";
		case 23:
			return "freefall";
		case 24:
			return "freefall_land";
		case 25:
			return "freefall_land_death";
		case 26:
			return "stand_to_jump_up";
		case 27:
			return "stand_to_jump_up_continue";
		case 28:
			return "jump_up";
		case 29:
			return "jump_up_to_hang_unused";
		case 30:
			return "jump_to_freefall";
		case 31:
			return "jump_to_land";
		case 32:
			return "smash_jump";
		case 33:
			return "smash_jump_continue";
		case 34:
			return "fall_start";
		case 35:
			return "fall";
		case 36:
			return "fall_to_freefall";
		case 37:
			return "hang_to_freefall_unused";
		case 38:
			return "walk_back_end_right";
		case 39:
			return "walk_back_end_left";
		case 40:
			return "walk_back";
		case 41:
			return "walk_back_start";
		case 42:
			return "climb_3click";
		case 43:
			return "climb_3click_end_to_run_unused";
		case 44:
			return "turn_right";
		case 45:
			return "jump_forward_to_freefall_continue";
		case 46:
			return "reach_to_freefall_unused";
		case 47:
			return "roll_alternate_unused";
		case 48:
			return "roll_end_alternate_unused";
		case 49:
			return "jump_forward_end_to_freefall_unused";
		case 50:
			return "climb_2click";
		case 51:
			return "climb_2click_end";
		case 52:
			return "climb_2click_end_to_run";
		case 53:
			return "wall_smash_left";
		case 54:
			return "wall_smash_right";
		case 55:
			return "run_up_step_right";
		case 56:
			return "run_up_step_left";
		case 57:
			return "walk_up_step_right";
		case 58:
			return "walk_up_step_left";
		case 59:
			return "walk_down_left";
		case 60:
			return "walk_down_right";
		case 61:
			return "walk_down_back_left";
		case 62:
			return "walk_down_back_right";
		case 63:
			return "wall_switch_down";
		case 64:
			return "wall_switch_up";
		case 65:
			return "sidestep_left";
		case 66:
			return "sidestep_left_end";
		case 67:
			return "sidestep_right";
		case 68:
			return "sidestep_right_end";
		case 69:
			return "rotate_left";
		case 70:
			return "slide_forwards";
		case 71:
			return "slide_forwards_end";
		case 72:
			return "slide_forwards_stop";
		case 73:
			return "stand_to_jump";
		case 74:
			return "jump_back_start";
		case 75:
			return "jump_back";
		case 76:
			return "jump_forwards_start";
		case 77:
			return "jump_forwards";
		case 78:
			return "jump_left_start";
		case 79:
			return "jump_left";
		case 80:
			return "jump_right_start";
		case 81:
			return "jump_right";
		case 82:
			return "land";
		case 83:
			return "jump_back_to_freefall";
		case 84:
			return "jump_left_to_freefall";
		case 85:
			return "jump_right_to_freefall";
		case 86:
			return "underwater_swim_forwards";
		case 87:
			return "underwater_swim_forwards_drift";
		case 88:
			return "small_jump_back_start";
		case 89:
			return "small_jump_back";
		case 90:
			return "small_jump_back_end";
		case 91:
			return "jump_up_start";
		case 92:
			return "land_to_run";
		case 93:
			return "fall_back";
		case 94:
			return "jump_forwards_to_reach";
		case 95:
			return "reach";
		case 96:
			return "reach_to_hang";
		case 97:
			return "climb_on";
		case 98:
			return "reach_to_freefall";
		case 99:
			return "fall_crouching_landing_unused";
		case 100:
			return "jump_forwards_to_reach_late_unused";
		case 101:
			return "jump_forwards_start_to_reach_alternate_unused";
		case 102:
			return "climb_on_end";
		case 103:
			return "stand_idle";
		case 104:
			return "slide_backwards_start";
		case 105:
			return "slide_backwards";
		case 106:
			return "slide_backwards_end";
		case 107:
			return "underwater_swim_to_idle";
		case 108:
			return "underwater_idle";
		case 109:
			return "underwater_idle_to_swim";
		case 110:
			return "on_water_idle";
		case 111:
			return "on_water_to_stand_high";
		case 112:
			return "freefall_to_underwater";
		case 113:
			return "on_water_dive_alternate_unused";
		case 114:
			return "underwater_to_on_water";
		case 115:
			return "on_water_swim_forwards_dive_unused";
		case 116:
			return "on_water_swim_forwards";
		case 117:
			return "on_water_swim_forwards_to_idle";
		case 118:
			return "on_water_idle_to_swim_forwards";
		case 119:
			return "on_water_dive";
		case 120:
			return "pushable_grab";
		case 121:
			return "pushable_release";
		case 122:
			return "pushable_pull";
		case 123:
			return "pushable_push";
		case 124:
			return "underwater_death";
		case 125:
			return "hit_front";
		case 126:
			return "hit_back";
		case 127:
			return "hit_left";
		case 128:
			return "hit_right";
		case 129:
			return "underwater_switch";
		case 130:
			return "underwater_pickup";
		case 131:
			return "use_key";
		case 132:
			return "on_water_death";
		case 133:
			return "run_death";
		case 134:
			return "use_puzzle";
		case 135:
			return "pickup";
		case 136:
			return "shimmy_left";
		case 137:
			return "shimmy_right";
		case 138:
			return "stand_death";
		case 139:
			return "boulder_death";
		case 140:
			return "on_water_idle_to_swim_back";
		case 141:
			return "on_water_swim_back";
		case 142:
			return "on_water_swim_back_to_idle";
		case 143:
			return "on_water_swim_left";
		case 144:
			return "on_water_swim_right";
		case 145:
			return "death_jump";
		case 146:
			return "roll_start";
		case 147:
			return "roll_continue";
		case 148:
			return "roll_end";
		case 149:
			return "spike_death";
		case 150:
			return "reach_to_thin_ledge";
		case 151:
			return "swandive_roll";
		case 152:
			return "swandive_to_underwater";
		case 153:
			return "freefall_swandive";
		case 154:
			return "freefall_swandive_to_underwater";
		case 155:
			return "swandive_death";
		case 156:
			return "swandive_left";
		case 157:
			return "swandive_right";
		case 158:
			return "swandive_start";
		case 159:
			return "climb_on_handstand";
		case 160:
			return "stand_to_ladder";
		case 161:
			return "ladder_up";
		case 162:
			return "ladder_up_stop_right";
		case 163:
			return "ladder_up_stop_left";
		case 164:
			return "ladder_idle";
		case 165:
			return "ladder_up_start";
		case 166:
			return "ladder_down_stop_left";
		case 167:
			return "ladder_down_stop_right";
		case 168:
			return "ladder_down";
		case 169:
			return "ladder_down_start";
		case 170:
			return "ladder_right";
		case 171:
			return "ladder_left";
		case 172:
			return "ladder_hang";
		case 173:
			return "ladder_hang_to_idle";
		case 174:
			return "ladder_climb_on";
		case 175:
			return "unknown_1";
		case 176:
			return "on_water_to_wade_shallow_unused";
		case 177:
			return "wade";
		case 178:
			return "run_to_wade_left";
		case 179:
			return "run_to_wade_right";
		case 180:
			return "wade_to_run_left";
		case 181:
			return "wade_to_run_right";
		case 182:
			return "ladder_backflip_start";
		case 183:
			return "ladder_backflip_continue";
		case 184:
			return "wade_to_stand_right";
		case 185:
			return "wade_to_stand_left";
		case 186:
			return "stand_to_wade";
		case 187:
			return "ladder_up_hanging";
		case 188:
			return "ladder_down_hanging";
		case 189:
			return "flare_throw";
		case 190:
			return "on_water_to_wade";
		case 191:
			return "on_water_to_stand_medium";
		case 192:
			return "underwater_to_stand";
		case 193:
			return "on_water_to_wade_low";
		case 194:
			return "ladder_to_hang_down";
		case 195:
			return "switch_small_down";
		case 196:
			return "switch_small_up";
		case 197:
			return "button_push";
		case 198:
			return "underwater_swim_to_still_huddle";
		case 199:
			return "underwater_swim_to_still_sprawl";
		case 200:
			return "underwater_swim_to_still_medium";
		case 201:
			return "ladder_to_hang_right";
		case 202:
			return "ladder_to_hang_left";
		case 203:
			return "underwater_roll_start";
		case 204:
			return "flare_pickup";
		case 205:
			return "underwater_roll_end";
		case 206:
			return "underwater_flare_pickup";
		case 207:
			return "run_jump_roll_start";
		case 208:
			return "somersault";
		case 209:
			return "run_jump_roll_end";
		case 210:
			return "jump_forwards_roll_start";
		case 211:
			return "jump_forwards_roll_end";
		case 212:
			return "jump_back_roll_start";
		case 213:
			return "jump_back_roll_end";
		case 214:
			if (p_level_format == TR2_PC) {
				return "kick";
			} else {
				return "zipline_grab";
			}
		case 215:
			if (p_level_format == TR2_PC) {
				return "zipline_grab";
			} else {
				return "zipline_ride";
			}
		case 216:
			if (p_level_format == TR2_PC) {
				return "zipline_ride";
			} else {
				return "zipline_fall";
			}
		case 217:
			if (p_level_format == TR2_PC) {
				return "zipline_fall";
			} else {
				return "stand_to_crouch";
			}
		case 218:
			return "crouch_roll_forwards_start_unused";
		case 219:
			return "crouch_roll_forwards_continue_unused";
		case 220:
			return "crouch_roll_forwards_end_unused";
		case 221:
			return "crouch_to_stand";
		case 222:
			return "crouch_idle";
		case 223:
			return "sprint";
		case 224:
			return "run_to_sprint_left";
		case 225:
			return "run_to_sprint_right";
		case 226:
			return "sprint_slide_stand_right";
		case 227:
			return "sprint_slide_stand_right_alternate";
		case 228:
			return "sprint_slide_stand_left";
		case 229:
			return "sprint_slide_stand_left_alternate";
		case 230:
			return "sprint_to_roll_left";
		case 231:
			return "sprint_to_roll_left_beta_unused";
		case 232:
			return "sprint_to_roll_left_to_run";
		case 233:
			return "monkey_grab";
		case 234:
			return "monkey_idle";
		case 235:
			return "monkey_fall";
		case 236:
			return "monkey_forwards";
		case 237:
			return "monkey_stop_left";
		case 238:
			return "monkey_stop_right";
		case 239:
			return "monkey_idle_to_forwards_left";
		case 240:
			return "sprint_to_roll_alternate_start_unused";
		case 241:
			return "sprint_to_roll_alternate_continue_unused";
		case 242:
			return "sprint_to_roll_alternate_end_unused";
		case 243:
			return "sprint_to_run_left";
		case 244:
			return "sprint_to_run_right";
		case 245:
			return "stand_to_crouch_end";
		case 246:
			return "slide_forwards_to_run";
		case 247:
			return "crouch_roll_forwards_start_alternate";
		case 248:
			return "jump_forwards_start_to_grab_early";
		case 249:
			return "jump_forwards_start_to_grab_late";
		case 250:
			return "run_to_grab_right";
		case 251:
			return "run_to_grab_left";
		case 252:
			return "monkey_idle_to_forwards_right";
		case 253:
			return "monkey_shimmy_left";
		case 254:
			return "monkey_shimmy_left_end";
		case 255:
			return "monkey_shimmy_right";
		case 256:
			return "monkey_shimmy_right_end";
		case 257:
			return "monkey_turn_around_unused";
		case 258:
			return "crouch_to_crawl_start";
		case 259:
			return "crawl_to_crouch_start";
		case 260:
			return "crawl_forwards";
		case 261:
			return "crawl_idle_to_forwards";
		case 262:
			return "crawl_forwards_to_idle_start_right";
		case 263:
			return "crawl_idle";
		case 264:
			return "crouch_to_crawl_end";
		case 265:
			return "crouch_to_crawl_end_unused";
		case 266:
			return "crawl_forwards_to_idle_end_right";
		case 267:
			return "crawl_forwards_to_idle_start_left";
		case 268:
			return "crawl_forwards_to_idle_end_left";
		case 269:
			return "crawl_turn_left";
		case 270:
			return "crawl_turn_right";
		case 271:
			return "monkey_turn_left";
		case 272:
			return "monkey_turn_right";
		case 273:
			return "crouch_to_crawl_continue";
		case 274:
			return "crawl_to_crouch_continue";
		case 275:
			return "crawl_idle_to_backwards";
		case 276:
			return "crawl_backwards";
		case 277:
			return "crawl_backwards_to_idle_right_start";
		case 278:
			return "crawl_backwards_to_idle_right_end";
		case 279:
			return "crawl_backwards_to_idle_left_start";
		case 280:
			return "crawl_backwards_to_idle_left_end";
		case 281:
			return "crawl_turn_left_early_end";
		case 282:
			return "crawl_turn_right_early_end";
		case 283:
			return "monkey_turn_left_early_end";
		case 284:
			return "monkey_turn_left_late_end";
		case 285:
			return "monkey_turn_right_early_end";
		case 286:
			return "monkey_turn_right_late_end";
		case 287:
			return "hang_to_crouch_start";
		case 288:
			return "hang_to_crouch_end";
		case 289:
			return "crawl_to_hang_start";
		case 290:
			return "crawl_to_hang_continue";
		case 291:
			return "crouch_pickup";
		case 292:
			return "crawl_pickup";
		case 293:
			return "crouch_hit_front";
		case 294:
			return "crouch_hit_back";
		case 295:
			return "crouch_hit_right";
		case 296:
			return "crouch_hit_left";
		case 297:
			return "crawl_hit_front";
		case 298:
			return "crawl_hit_back";
		case 299:
			return "crawl_hit_right";
		case 300:
			return "crawl_hit_left";
		case 301:
			return "crawl_death";
		case 302:
			return "crawl_to_hang_end";
		case 303:
			return "stand_to_crouch_abort_unused";
		case 304:
			return "run_to_crouch_left_start";
		case 305:
			return "run_to_crouch_right_start";
		case 306:
			return "run_to_crouch_left_end";
		case 307:
			return "run_to_crouch_right_end";
		case 308:
			return "sprint_to_roll_right";
		case 309:
			return "sprint_roll_right_to_run";
		case 310:
			return "sprint_to_crouch_left";
		case 311:
			return "sprint_to_crouch_right";
		case 312:
			return "crouch_pickup_flare";
		case 313:
			return "door_open_forward";
		case 314:
			return "door_open_back";
		case 315:
			return "door_kick";
		case 316:
			return "giant_button_psuh";
		case 317:
			return "floor_trapdoor_open";
		case 318:
			return "ceiling_trapdoor_open";
		case 319:
			return "turnswitch_grab_left";
		case 320:
			return "turnswitch_grab_right";
		case 321:
			return "cogwheel_pull";
		case 322:
			return "cogwheel_grab";
		case 323:
			return "cogwheel_ungrab";
		case 324:
			return "leverswitch_push";
		case 325:
			return "hole_grab";
		case 326:
			return "stand_to_pole_grab";
		case 327:
			return "pole_jump";
		case 328:
			return "pole_idle";
		case 329:
			return "pole_climb_up";
		case 330:
			return "pole_fall";
		case 331:
			return "reach_to_pole_grab";
		case 332:
			return "pole_turn_left_start";
		case 333:
			return "pole_turn_right_start";
		case 334:
			return "pole_idle_to_climb_down";
		case 335:
			return "pole_climb_down";
		case 336:
			return "pole_climb_down_to_idle";
		case 337:
			return "jump_up_to_pole_grab";
		case 338:
			return "pole_climb_up_end";
		case 339:
			return "pulley_grab";
		case 340:
			return "pulley_pull";
		case 341:
			return "pulley_ungrab";
		case 342:
			return "pole_grab_to_stand";
		case 343:
			return "pole_turn_left_continue_unused";
		case 344:
			return "pole_turn_left_end";
		case 345:
			return "pole_turn_right_continue_unused";
		case 346:
			return "pole_turn_right_end";
		case 347:
			return "turnswitch_push_right_start";
		case 348:
			return "turnswitch_push_right_continue";
		case 349:
			return "turnswitch_push_right_send";
		case 350:
			return "turnswitch_push_left_start";
		case 351:
			return "turnswitch_push_left_continue";
		case 352:
			return "turnswitch_push_left_send";
		case 353:
			return "crouch_turn_left";
		case 354:
			return "crouch_turn_right";
		case 355:
			return "hang_corner_left_outer_start";
		case 356:
			return "hang_corner_left_outer_end";
		case 357:
			return "hang_corner_right_outer_start";
		case 358:
			return "hang_corner_right_outer_end";
		case 359:
			return "hang_corner_left_inner_start";
		case 360:
			return "hang_corner_left_inner_end";
		case 361:
			return "hang_corner_right_inner_start";
		case 362:
			return "hang_corner_right_inner_end";
		case 363:
			return "ladder_corner_left_outer_start";
		case 364:
			return "ladder_corner_left_outer_end";
		case 365:
			return "ladder_corner_right_outer_start";
		case 366:
			return "ladder_corner_right_outer_end";
		case 367:
			return "ladder_corner_left_inner_start";
		case 368:
			return "ladder_corner_left_inner_end";
		case 369:
			return "ladder_corner_right_inner_start";
		case 370:
			return "ladder_corner_right_inner_end";
		case 371:
			return "jump_up_to_rope_start";
		case 372:
			return "train_death";
		case 373:
			return "jump_up_to_rope_end";
		case 374:
			return "rope_idle";
		case 375:
			return "rope_down_start";
		case 376:
			return "rope_up";
		case 377:
			return "rope_idle_to_rope_hang_unused";
		case 378:
			return "rope_grab_to_fall_unused";
		case 379:
			return "rope_jump_to_grab";
		case 380:
			return "rope_idle_to_backflip_unused";
		case 381:
			return "rope_swing_to_fall_semi_front_unused";
		case 382:
			return "rope_swing_to_fall_middle_unused";
		case 383:
			return "rope_swing_to_fall_back_unused";
		case 384:
			return "rope_down";
		case 385:
			return "rope_down_end";
		case 386:
			return "rope_swing_to_reach";
		case 387:
			return "rope_idle_to_swing";
		case 388:
			return "rope_idle_to_swing_semi_middle_unused";
		case 389:
			return "rope_idle_to_swing_half_middle_unused";
		case 390:
			return "rope_swing_to_fall_front_unused";
		case 391:
			return "rope_grab_to_fall_alternate_unused";
		case 392:
			return "rope_turn_left";
		case 393:
			return "rope_turn_right";
		case 394:
			return "rope_swing";
		case 395:
			return "ladder_to_hands_down_alternate_unused";
		case 396:
			return "rope_swing_back_continue_unused";
		case 397:
			return "rope_swing_back_end_unused";
		case 398:
			return "rope_swing_back_start_unused";
		case 399:
			return "rope_swing_forward_soft_unused";
		case 400:
			return "pour_waterskin_low";
		case 401:
			return "fill_waterskin";
		case 402:
			return "pour_waterskin_high";
		case 403:
			return "pry_door";
		case 404:
			return "rope_swing_forward_hard_unused";
		case 405:
			return "rope_change_rope_unused";
		case 406:
			return "rope_swing_to_reach_front";
		case 407:
			return "rope_swing_to_reach_middle";
		case 408:
			return "rope_swing_block_unused";
		case 409:
			return "rope_swing_to_reach_semi_middle";
		case 410:
			return "rope_swing_to_reach_hang_front";
		case 411:
			return "rope_swing_to_reach_front2";
		case 412:
			return "double_doors_push";
		case 413:
			return "big_button_push";
		case 414:
			return "jumpswitch";
		case 415:
			return "underwater_pulley";
		case 416:
			return "underwater_door_open";
		case 417:
			return "pushable_push_to_stand";
		case 418:
			return "pushable_pull_to_stand";
		case 419:
			return "crowbar_use_on_wall";
		case 420:
			return "crowbar_use_on_floor";
		case 421:
			return "crawl_jump_down";
		case 422:
			return "harp_play";
		case 423:
			return "put_trident";
		case 424:
			return "pickup_pedestal_high";
		case 425:
			return "pickup_pedestal_low";
		case 426:
			return "rotate_senet";
		case 427:
			return "torch_light_1";
		case 428:
			return "torch_light_2";
		case 429:
			return "torch_light_3";
		case 430:
			return "torch_light_4";
		case 431:
			return "torch_light_5";
		case 432:
			return "detonator_use";
		case 433:
			return "correct_position_front_unused";
		case 434:
			return "correct_position_left_unused";
		case 435:
			return "correct_position_right_unused";
		case 436:
			return "crowbar_use_on_floor_fail_unused";
		case 437:
			return "use_keycard";
		case 438:
			return "death_blowup";
		case 439:
			return "pickup_sarcophagus";
		case 440:
			return "drag_body";
		case 441:
			return "binoculars";
		case 442:
			return "death_big_scorpion";
		case 443:
			return "elevator_smash";
		case 444:
			return "beetle_put";
		case 445:
			return "dozy";
		case 446:
			return "tightrope_walk";
		case 447:
			return "tightrope_walk_to_stand";
		case 448:
			return "tightrope_stand";
		case 449:
			return "tightrope_walk_to_stand_careful";
		case 450:
			return "tightrope_stand_to_walk";
		case 451:
			return "tightrope_turn";
		case 452:
			return "tightrope_loose_left";
		case 453:
			return "tightrope_recover_left";
		case 454:
			return "tightrope_fall_left";
		case 455:
			return "tightrope_loose_right";
		case 456:
			return "tightrope_recover_right";
		case 457:
			return "tightrope_fall_right";
		case 458:
			return "tightrope_start";
		case 459:
			return "tightrope_finish";
		case 460:
			return "doveswitch_turn";
		case 461:
			return "bars_grab";
		case 462:
			return "bars_swing";
		case 463:
			return "bars_jump";
		case 464:
			return "loot_cabinet";
		case 465:
			return "loot_drawer";
		case 466:
			return "loot_shelf";
		case 467:
			return "radio_start";
		case 468:
			return "radio_idle";
		case 469:
			return "radio_end";
		case 470:
			return "valve_turn";
		case 471:
			return "crowbar_use_on_wall";
		case 472:
			return "loot_chest";
		case 473:
			return "ladder_to_crouch";
	}
	return String("animation_") + itos(p_animation_id);
}


static String get_lara_bone_name(size_t p_bone_id) {
	switch (p_bone_id) {
		case 0:
			return "Hips";
		case 1:
			return "LeftUpperLeg";
		case 2:
			return "LeftLowerLeg";
		case 3:
			return "LeftFoot";
		case 4:
			return "RightUpperLeg";
		case 5:
			return "RightLowerLeg";
		case 6:
			return "RightFoot";
		case 7:
			return "Spine";
		case 8:
			return "RightUpperArm";
		case 9:
			return "RightLowerArm";
		case 10:
			return "RightHand";
		case 11:
			return "LeftUpperArm";
		case 12:
			return "LeftLowerArm";
		case 13:
			return "LeftHand";
		case 14:
			return "Head";
	}
	return String("bone_") + itos(p_bone_id);
}

#include "tr_names_tr1.hpp"
#include "tr_names_tr2.hpp"
#include "tr_names_tr3.hpp"
#include "tr_names_tr4.hpp"
#include "tr_level_data.hpp"

static String get_type_info_name(uint32_t p_type_info_id, TRLevelFormat p_level_format) {
	switch(p_level_format) {
	case TRLevelFormat::TR1_PC:
		return get_tr1_type_info_name(p_type_info_id);
	case TRLevelFormat::TR2_PC:
		return get_tr2_type_info_name(p_type_info_id);
	case TRLevelFormat::TR3_PC:
		return get_tr3_type_info_name(p_type_info_id);
	case TRLevelFormat::TR4_PC:
		return get_tr4_type_info_name(p_type_info_id);
	default:
		return String("MoveableInfo_") + itos(p_type_info_id);
	}
}

extern bool is_lara_compatible_humanoid(uint32_t p_type_info_id, TRLevelFormat p_level_format);

static String get_bone_name(uint32_t p_type_info_id, uint32_t p_bone_id, TRLevelFormat p_level_format) {
	if (is_lara_compatible_humanoid(p_type_info_id, p_level_format)) {
		return get_lara_bone_name(p_bone_id);
	}

	switch (p_level_format) {
		case TRLevelFormat::TR1_PC:
			return get_tr1_bone_name(p_type_info_id, p_bone_id);
		case TRLevelFormat::TR2_PC:
			return get_tr2_bone_name(p_type_info_id, p_bone_id);
		case TRLevelFormat::TR3_PC:
			return get_tr3_bone_name(p_type_info_id, p_bone_id);
		case TRLevelFormat::TR4_PC:
			return get_tr4_bone_name(p_type_info_id, p_bone_id);
		default:
			return String("bone_") + itos(p_bone_id);
	}
}

static String get_animation_name(uint32_t p_type_info_id, uint32_t p_animation_id, TRLevelFormat p_level_format) {
	switch (p_level_format) {
		case TRLevelFormat::TR1_PC:
			return get_tr1_animation_name(p_type_info_id, p_animation_id);
		case TRLevelFormat::TR2_PC:
			return get_tr2_animation_name(p_type_info_id, p_animation_id);
		case TRLevelFormat::TR3_PC:
			return get_tr3_animation_name(p_type_info_id, p_animation_id);
		case TRLevelFormat::TR4_PC:
			return get_tr4_animation_name(p_type_info_id, p_animation_id);
		default:
			return String("animation_") + itos(p_animation_id);
	}
}

static String get_default_state_name(uint32_t p_state_id) {
	return String("state_") + itos(p_state_id);
}

static String get_lara_state_name(uint32_t p_state_id) {
	switch (p_state_id) {
		case 0:
			return "WalkForwards";
		case 1:
			return "RunForwards";
		case 2:
			return "Stop";
		case 3:
			return "ForwardJump";
		case 4:
			return "Pose";
		case 5:
			return "HopBackwards";
		case 6:
			return "TurnRight";
		case 7:
			return "TurnLeft";
		case 8:
			return "Death";
		case 9:
			return "FastFall";
		case 10:
			return "Hang";
		case 11:
			return "Reach";
		case 12:
			return "FallDeath";
		case 13:
			return "UnderwaterStop";
		case 14:
			return "Land";
		case 15:
			return "Compress";
		case 16:
			return "WalkBackwards";
		case 17:
			return "UnderwaterSwim";
		case 18:
			return "UnderwaterGlide";
		case 19:
			return "Grabbing";
		case 20:
			return "FastTurn";
		case 21:
			return "StepRight";
		case 22:
			return "StepLeft";
		case 23:
			return "AltRoll";
		case 24:
			return "SlideForwards";
		case 25:
			return "BackwardsJump";
		case 26:
			return "RightJump";
		case 27:
			return "LeftJump";
		case 28:
			return "UpJump";
		case 29:
			return "FallBack";
		case 30:
			return "ShimmyLeft";
		case 31:
			return "ShimmyRight";
		case 32:
			return "SlideBackwards";
		case 33:
			return "OnWaterIdle";
		case 34:
			return "OnWaterSwimForwards";
		case 35:
			return "Dive";
		case 36:
			return "PushBlock";
		case 37:
			return "PullBlock";
		case 38:
			return "PushPullReady";
		case 39:
			return "Pickup";
		case 40:
			return "SwitchOn";
		case 41:
			return "SwitchOff";
		case 42:
			return "InsertKey";
		case 43:
			return "InsertPuzzle";
		case 44:
			return "UnderwaterDeath";
		case 45:
			return "Roll";
		case 46:
			return "Special";
		case 47:
			return "OnWaterSwimBackwards";
		case 48:
			return "OnWaterSwimLeft";
		case 49:
			return "OnWaterSwimRight";
		case 50:
			return "UseMidasPuzzle";
		case 51:
			return "MidasPuzzleDeath";
		case 52:
			return "SwanDiveBegin";
		case 53:
			return "SwanDiveEnd";
		case 54:
			return "Handstand";
		case 55:
			return "OnWaterExit";
		case 56:
			return "OnLadderIdle";
		case 57:
			return "OnLadderUp";
		case 58:
			return "OnLadderLeft";
		case 59:
			return "OnLadderStop";
		case 60:
			return "OnLadderRight";
		case 61:
			return "OnLadderDown";
		case 62:
			return "Test1";
		case 63:
			return "Test2";
		case 64:
			return "Test3";
		case 65:
			return "WadeForwards";
		case 66:
			return "UnderwaterRoll";
		case 67:
			return "FlarePickup";
		case 68:
			return "SwanDiveRoll";
		case 69:
			return "Kick";
		case 70:
			return "ZiplineRide";
		case 71:
			return "CrouchIdle";
		case 72:
			return "CrouchRoll";
		case 73:
			return "Sprint";
		case 74:
			return "SprintRoll";
		case 75:
			return "MonkeyIdle";
		case 76:
			return "MonkeyForwards";
		case 77:
			return "MonkeyLeft";
		case 78:
			return "MonkeyRight";
		case 79:
			return "MonkeyRoll";
		case 80:
			return "CrawlIdle";
		case 81:
			return "CrawlForward";
		case 82:
			return "MonkeyTurnLeft";
		case 83:
			return "MonkeyTurnRight";
		case 84:
			return "CrawlTurnLeft";
		case 85:
			return "CrawlTurnRight";
		case 86:
			return "CrawlBackwards";
		case 87:
			return "ClimbToCrawl";
		case 88:
			return "CrawlToClimb";
		case 89:
			return "MiscControlled";
		case 90:
			return "RopeTurnLeft";
		case 91:
			return "RopeTurnRight";
		case 92:
			return "GiantButtonPush";
		case 93:
			return "TrapdoorFloorOpen";
		case 94:
			return "TrapdoorCeilingOpen";
		case 95:
			return "RoundHandle";
		case 96:
			return "CogWheel";
		case 97:
			return "LeverSwitchPush";
		case 98:
			return "Hole";
		case 99:
			return "PoleIdle";
		case 100:
			return "PoleUp";
		case 101:
			return "PoleDown";
		case 102:
			return "PoleTurnLeft";
		case 103:
			return "PoleTurnRight";
		case 104:
			return "Pulley";
		case 105:
			return "CrouchTurnLeft";
		case 106:
			return "CrouchTurnRight";
		case 107:
			return "ShimmyOuterLeft";
		case 108:
			return "ShimmyOuterRight";
		case 109:
			return "ShimmyInnerLeft";
		case 110:
			return "ShimmyInnerRight";
		case 111:
			return "RopeIdle";
		case 112:
			return "RopeClimbUp";
		case 113:
			return "RopeClimbDown";
		case 114:
			return "RopeSwing";
		case 115:
			return "LadderToShimmy";
		case 116:
			return "PositionCorrector";
		case 117:
			return "DoubleDoorsPush";
		case 118:
			return "Dozy";
		default:
			return get_default_state_name(p_state_id);
	}
}

static String get_state_name(uint32_t p_type_info_id, uint32_t p_state_id, TRLevelFormat p_level_format) {
	switch (p_type_info_id) {
		case 0:
			return get_lara_state_name(p_state_id);
			break;
		default:
			return get_default_state_name(p_state_id);
			break;
	}
}